services:
  racoder:
    build: .
    container_name: racoder
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    environment:
      DEFAULT_BITRATE: 128
      OUTPUT_PATH: '/play'
      TZ: Europe/Berlin
      LOG_LEVEL: DEBUG
    read_only: true
    cap_drop:
      - ALL