# fly.toml app configuration file generated for racoder on 2023-06-18T12:26:44+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "racoder"
primary_region = "ams"

[build]
  image = "paulgalow/racoder:latest"
  #dockerfile = "Dockerfile"

[deploy]
  strategy = "immediate"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [services.concurrency]
    type = "connections"
    soft_limit = 10
    hard_limit = 20
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = false
  #[[services.ports]]
  #  handlers = ["tls", "http"]
  #  port = 443
  [[services.http_checks]]
    interval = 30000
    grace_period = "5s"
    method = "get"
    path = "/healthcheck"
    protocol = "http"
    timeout = 5000
    tls_skip_verify = false

[env]
  # See: https://gist.github.com/bpsib/67089b959e4fa898af69fea59ad74bc3 or https://en.everybodywiki.com/List_of_BBC_radio_stream_URLs
  INPUT_STREAM = "https://as-hls-ww-live.akamaized.net/pool_904/live/ww/bbc_radio_four_extra/bbc_radio_four_extra.isml/bbc_radio_four_extra-audio%3d96000.norewind.m3u8"
  OUTPUT_PATH = "/bbc-radio-4-extra"
  BITRATE = "128k"
  TZ = "Europe/Berlin"
  #LOG_LEVEL = "DEBUG"