services:
  racoder:
    image: paulgalow/racoder:latest
    container_name: racoder
    restart: unless-stopped
    ports:
      - "3000:3000/tcp"
    environment:
      INPUT_STREAM: "https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_radio_four_extra.m3u8"
      OUTPUT_PATH: "/bbc-radio-4-extra"
      BITRATE: 128k
      TZ: Europe/Berlin
      LOG_LEVEL: DEBUG
    read_only: true
    cap_drop:
      - ALL

networks:
  default:
