# See https://fly.io/docs/reference/configuration/ for information about how to use this file.

[build]
  image = "paulgalow/racoder:latest"

[[services]]
  internal_port = 3000
  protocol = "tcp"
  auto_stop_machines = false
  auto_start_machines = false
  min_machines_running = 1
  [[services.ports]]
    handlers = ["http"]
    port = 80
    force_https = false

[env]
  INPUT_STREAM = "https://a.files.bbci.co.uk/media/live/manifesto/audio/simulcast/hls/nonuk/sbr_low/ak/bbc_radio_four_extra.m3u8"
  # Output stream will be available at "/"